#!/bin/sh

rm RelSource.zip
cd ..
zip -9r _Deployment/RelSource.zip DBrowser Shared Client Server* Tests Rev -x@RelDeployment/exclude.lst
cd /home/dave/IzPack/bin
./compile /home/dave/git/Rel/RelDeployment/install.xml -b /home/dave/git/Rel/RelDeployment -o /home/dave/git/Rel/RelDeployment/install.jar
cd /home/dave/git/Rel/RelDeployment
mv install.jar RelInstall-1.0.13.jar
jjdoc -ONE_TABLE=false /home/dave/git/Rel/ServerV000/org/reldb/rel/v0/languages/tutoriald/parser/TutorialD.jj
