#!/bin/sh

rm RelSource.zip
cd ..
zip -9r RelDeployment/RelSource.zip Rel3DBrowser Rel3Shared Rel3Client Rel3Server Rel3Test Rel3Test Rev -x@RelDeployment/exclude.lst
cd /home/dave/IzPack/bin
./compile /home/dave/git/Rel/RelDeployment/install.xml -b /home/dave/git/Rel/RelDeployment -o /home/dave/git/Rel/RelDeployment/install.jar
cd /home/dave/git/Rel/RelDeployment
mv install.jar RelInstall-1.0.13.jar
jjdoc -ONE_TABLE=false /home/dave/git/Rel/Rel3Server/ca/mb/armchair/rel3/languages/tutoriald/parser/TutorialD.jj
