/* Generated By:JJTree: Do not edit this line. ASTBooleanExpressionCommalist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTBooleanExpressionCommalist extends SimpleNode {
  public ASTBooleanExpressionCommalist(int id) {
    super(id);
  }

  public ASTBooleanExpressionCommalist(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b37da16123b8efdeb5cf6ec80979a63f (do not edit this line) */
