/* Generated By:JJTree: Do not edit this line. ASTDerivedPossrepComponentDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTDerivedPossrepComponentDef extends SimpleNode {
  public ASTDerivedPossrepComponentDef(int id) {
    super(id);
  }

  public ASTDerivedPossrepComponentDef(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cd8e72d099592c3ee74d83bf39b34a6d (do not edit this line) */
