/* Generated By:JJTree: Do not edit this line. ASTFnInvokeAnonymous.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTFnInvokeAnonymous extends SimpleNode {
  public ASTFnInvokeAnonymous(int id) {
    super(id);
  }

  public ASTFnInvokeAnonymous(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=534640fce006bc306f51be7d2f7bfd1e (do not edit this line) */
