/* Generated By:JJTree: Do not edit this line. ASTMultipleInheritanceIsDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTMultipleInheritanceIsDef extends SimpleNode {
  public ASTMultipleInheritanceIsDef(int id) {
    super(id);
  }

  public ASTMultipleInheritanceIsDef(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28d620febe8b3bc1406d0b89d1f411f9 (do not edit this line) */
