/* Generated By:JJTree: Do not edit this line. ASTSummarizeAvgDistinct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTSummarizeAvgDistinct extends SimpleNode {
  public ASTSummarizeAvgDistinct(int id) {
    super(id);
  }

  public ASTSummarizeAvgDistinct(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b8fb24867c8d8be8e908314ab8378931 (do not edit this line) */
