/* Generated By:JJTree: Do not edit this line. ASTSingleInheritanceIsDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTSingleInheritanceIsDef extends SimpleNode {
  public ASTSingleInheritanceIsDef(int id) {
    super(id);
  }

  public ASTSingleInheritanceIsDef(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69652dbcdb8eb2a2d7d31c8bd962d1ea (do not edit this line) */
