/* Generated By:JJTree: Do not edit this line. ASTSummarizeSumDistinct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTSummarizeSumDistinct extends SimpleNode {
  public ASTSummarizeSumDistinct(int id) {
    super(id);
  }

  public ASTSummarizeSumDistinct(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a2c46d7fa645abbc2e54f86921cb4a7f (do not edit this line) */
