/* Generated By:JJTree: Do not edit this line. ASTSummarizeExactlyDistinct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTSummarizeExactlyDistinct extends SimpleNode {
  public ASTSummarizeExactlyDistinct(int id) {
    super(id);
  }

  public ASTSummarizeExactlyDistinct(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=182f362f80d1b2027df221498f97999f (do not edit this line) */
