/* Generated By:JJTree: Do not edit this line. ASTTupleExpressionCommalist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTTupleExpressionCommalist extends SimpleNode {
  public ASTTupleExpressionCommalist(int id) {
    super(id);
  }

  public ASTTupleExpressionCommalist(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8626381399c43eb42fc254f158a3c3c0 (do not edit this line) */
