/* Generated By:JJTree: Do not edit this line. ASTTypeSameTypeAs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTTypeSameTypeAs extends SimpleNode {
  public ASTTypeSameTypeAs(int id) {
    super(id);
  }

  public ASTTypeSameTypeAs(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52e0a5708fb31d0a5e07f670c838c28a (do not edit this line) */
