/* Generated By:JJTree: Do not edit this line. ASTTypeDefInternalOptOrdinal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTTypeDefInternalOptOrdinal extends SimpleNode {
  public ASTTypeDefInternalOptOrdinal(int id) {
    super(id);
  }

  public ASTTypeDefInternalOptOrdinal(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=65d2799d34ab663178f45c639d656384 (do not edit this line) */
