/* Generated By:JJTree: Do not edit this line. ASTTypeDefInternalOptUnion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTTypeDefInternalOptUnion extends SimpleNode {
  public ASTTypeDefInternalOptUnion(int id) {
    super(id);
  }

  public ASTTypeDefInternalOptUnion(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8432d42512fbba47815a8ad7e641ae23 (do not edit this line) */
