/* Generated By:JJTree: Do not edit this line. ASTVarTypeAndOptionalInit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTVarTypeAndOptionalInit extends SimpleNode {
  public ASTVarTypeAndOptionalInit(int id) {
    super(id);
  }

  public ASTVarTypeAndOptionalInit(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49bf21f1d85a3751dd347b145d86df7b (do not edit this line) */
