/* Generated By:JJTree: Do not edit this line. ASTWithNameIntroCommalist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=ca.mb.armchair.rel3.languages.tutoriald.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public
class ASTWithNameIntroCommalist extends SimpleNode {
  public ASTWithNameIntroCommalist(int id) {
    super(id);
  }

  public ASTWithNameIntroCommalist(TutorialD p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TutorialDVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4991b0d54360ed6621fb90279b2353d3 (do not edit this line) */
