/* Generated By:JavaCC: Do not edit this line. TutorialDTreeConstants.java Version 5.0 */
package ca.mb.armchair.rel3.languages.tutoriald.parser;

public interface TutorialDTreeConstants
{
  public int JJTEVALUATE = 0;
  public int JJTCODE = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTGETOPERATORRETURNTYPE = 4;
  public int JJTGETHEADING = 5;
  public int JJTGETSIGNATURE = 6;
  public int JJTWRITE = 7;
  public int JJTWRITELN = 8;
  public int JJTOUTPUT = 9;
  public int JJTANNOUNCE = 10;
  public int JJTEXECUTE = 11;
  public int JJTSET = 12;
  public int JJTLAMBDA = 13;
  public int JJTEXTERNALOPDEF = 14;
  public int JJTUSEROPDEF = 15;
  public int JJTUSEROPRETURNS = 16;
  public int JJTUSEROPUPDATES = 17;
  public int JJTUSEROPSYNONYM = 18;
  public int JJTUSEROPVERSION = 19;
  public int JJTUSEROPBODY = 20;
  public int JJTRETURNEXPRESSION = 21;
  public int JJTUSEROPPARAMETERS = 22;
  public int JJTPARMDEF = 23;
  public int JJTDROPOPERATOR = 24;
  public int JJTDROPRELVAR = 25;
  public int JJTDROPCONSTRAINT = 26;
  public int JJTDROPTYPE = 27;
  public int JJTOPSIGNATURE = 28;
  public int JJTOPTYPE = 29;
  public int JJTTYPEREFCOMMALIST = 30;
  public int JJTTYPEDEF = 31;
  public int JJTTYPEDEFEXTERNAL = 32;
  public int JJTTYPEDEFINTERNAL = 33;
  public int JJTTYPEDEFINTERNALOPTORDINAL = 34;
  public int JJTTYPEDEFINTERNALOPTORDERED = 35;
  public int JJTTYPEDEFINTERNALOPTUNION = 36;
  public int JJTSINGLEINHERITANCEISDEF = 37;
  public int JJTMULTIPLEINHERITANCEISDEF = 38;
  public int JJTSCALARTYPENAME = 39;
  public int JJTPOSSREPINITIALISER = 40;
  public int JJTPOSSREPINITIALISERASSIGNMENTS = 41;
  public int JJTPOSSREPDEF = 42;
  public int JJTPOSSREPDEFIDENTIFIER = 43;
  public int JJTPOSSREPDEFCONSTRAINTDEF = 44;
  public int JJTPOSSREPDEFCOMPONENTCOMMALIST = 45;
  public int JJTPOSSREPDEFCOMPONENT = 46;
  public int JJTPOSSREPCONSTRAINTDEF = 47;
  public int JJTSPECIALISATIONCONSTRAINTDEF = 48;
  public int JJTDERIVEDPOSSREPDEF = 49;
  public int JJTDERIVEDPOSSREPDEFOPTIDENTIFIER = 50;
  public int JJTDERIVEDPOSSREPCOMPONENTDEF = 51;
  public int JJTVARDEF = 52;
  public int JJTVARRELVARREAL = 53;
  public int JJTVARRELVARPRIVATE = 54;
  public int JJTVARRELVARPUBLIC = 55;
  public int JJTVARRELVARVIRTUAL = 56;
  public int JJTVARRELVAREXTERNAL = 57;
  public int JJTKEYDEFLIST = 58;
  public int JJTKEYDEF = 59;
  public int JJTVARSCALARORTUPLE = 60;
  public int JJTVARTYPEANDOPTIONALINIT = 61;
  public int JJTVARINIT = 62;
  public int JJTVARARRAY = 63;
  public int JJTDATABASECONSTRAINT = 64;
  public int JJTTYPE = 65;
  public int JJTTYPESAMETYPEAS = 66;
  public int JJTTYPETUPLE = 67;
  public int JJTTYPERELATION = 68;
  public int JJTSAMEHEADINGAS = 69;
  public int JJTRELATIONARRAYLOAD = 70;
  public int JJTTRANSACTIONBEGIN = 71;
  public int JJTTRANSACTIONCOMMIT = 72;
  public int JJTTRANSACTIONROLLBACK = 73;
  public int JJTCASESTATEMENT = 74;
  public int JJTCASEWHENLIST = 75;
  public int JJTCASEWHEN = 76;
  public int JJTCASEELSE = 77;
  public int JJTIFSTATEMENT = 78;
  public int JJTELSESTATEMENT = 79;
  public int JJTDOLOOP = 80;
  public int JJTWHILELOOP = 81;
  public int JJTFORLOOP = 82;
  public int JJTCALL = 83;
  public int JJTASSIGNMENT = 84;
  public int JJTASSIGN = 85;
  public int JJTINSERT = 86;
  public int JJTDINSERT = 87;
  public int JJTDELETE = 88;
  public int JJTIDELETE = 89;
  public int JJTUPDATESTATEMENT = 90;
  public int JJTDELETEPARAMETER = 91;
  public int JJTDELETEWHERE = 92;
  public int JJTUPDATEWHERE = 93;
  public int JJTUPDATEASSIGNMENT = 94;
  public int JJTEXPRESSION = 95;
  public int JJTATTRIBUTEFROM = 96;
  public int JJTTUPLEFROM = 97;
  public int JJTWITH = 98;
  public int JJTWITHNAMEINTROCOMMALIST = 99;
  public int JJTWITHNAMEINTRO = 100;
  public int JJTTCLOSE = 101;
  public int JJTARRAYDEREFERENCE = 102;
  public int JJTFNINVOKEANONYMOUS = 103;
  public int JJTALGORDER = 104;
  public int JJTALGWHERE = 105;
  public int JJTOR = 106;
  public int JJTXOR = 107;
  public int JJTAND = 108;
  public int JJTCOMPEQUAL = 109;
  public int JJTCOMPNEQUAL = 110;
  public int JJTCOMPGTE = 111;
  public int JJTCOMPLTE = 112;
  public int JJTCOMPGT = 113;
  public int JJTCOMPLT = 114;
  public int JJTTUPLEIN = 115;
  public int JJTALGUNION = 116;
  public int JJTALGXUNION = 117;
  public int JJTALGDUNION = 118;
  public int JJTALGINTERSECT = 119;
  public int JJTALGMINUS = 120;
  public int JJTALGIMINUS = 121;
  public int JJTALGJOIN = 122;
  public int JJTALGTIMES = 123;
  public int JJTALGCOMPOSE = 124;
  public int JJTALGSEMIJOIN = 125;
  public int JJTALGSEMIMINUS = 126;
  public int JJTALGRENAME = 127;
  public int JJTALGWRAP = 128;
  public int JJTALGUNWRAP = 129;
  public int JJTALGUNGROUP = 130;
  public int JJTALGDIVIDE = 131;
  public int JJTORDERITEMCOMMALIST = 132;
  public int JJTORDERITEMASC = 133;
  public int JJTORDERITEMDESC = 134;
  public int JJTALGDIVIDEPEROPTIONAL = 135;
  public int JJTALGPROJECT = 136;
  public int JJTGROUP = 137;
  public int JJTWRAPPINGITEM = 138;
  public int JJTRENAMINGLIST = 139;
  public int JJTRENAMINGSIMPLE = 140;
  public int JJTRENAMINGPREFIX = 141;
  public int JJTRENAMINGSUFFIX = 142;
  public int JJTATTRIBUTENAMELIST = 143;
  public int JJTALLBUT = 144;
  public int JJTATTRIBUTENAMECOMMALIST = 145;
  public int JJTADD = 146;
  public int JJTSUBTRACT = 147;
  public int JJTCONCATENATE = 148;
  public int JJTTIMES = 149;
  public int JJTDIVIDE = 150;
  public int JJTUNARYNOT = 151;
  public int JJTUNARYPLUS = 152;
  public int JJTUNARYMINUS = 153;
  public int JJTCASEEXPRESSION = 154;
  public int JJTCASEWHENLISTEXPRESSION = 155;
  public int JJTCASEWHENEXPRESSION = 156;
  public int JJTIFEXPRESSION = 157;
  public int JJTSUBSTITUTE = 158;
  public int JJTNADICHEADING = 159;
  public int JJTNADICUNION = 160;
  public int JJTNADICXUNION = 161;
  public int JJTNADICDUNION = 162;
  public int JJTNADICINTERSECT = 163;
  public int JJTNADICJOIN = 164;
  public int JJTNADICTIMES = 165;
  public int JJTNADICCOMPOSE = 166;
  public int JJTNADICOR = 167;
  public int JJTNADICXOR = 168;
  public int JJTNADICAND = 169;
  public int JJTNADICCOUNT = 170;
  public int JJTNADICSUM = 171;
  public int JJTNADICAVG = 172;
  public int JJTNADICMAX = 173;
  public int JJTNADICMIN = 174;
  public int JJTEXACTLY = 175;
  public int JJTEXPRESSIONCOMMALIST = 176;
  public int JJTBOOLEANEXPRESSIONCOMMALIST = 177;
  public int JJTHEADINGEXPCOMMALIST = 178;
  public int JJTEXTEND = 179;
  public int JJTEXTENDLIST = 180;
  public int JJTEXTENDITEM = 181;
  public int JJTSUMMARIZE = 182;
  public int JJTSUMMARIZEPERORBY = 183;
  public int JJTSUMMARIZEPER = 184;
  public int JJTSUMMARIZEBY = 185;
  public int JJTSUMMARIZEITEMS = 186;
  public int JJTSUMMARIZEITEM = 187;
  public int JJTSUMMARIZECOUNT = 188;
  public int JJTSUMMARIZECOUNTDISTINCT = 189;
  public int JJTSUMMARIZESUM = 190;
  public int JJTSUMMARIZESUMDISTINCT = 191;
  public int JJTSUMMARIZEAVG = 192;
  public int JJTSUMMARIZEAVGDISTINCT = 193;
  public int JJTSUMMARIZEMAX = 194;
  public int JJTSUMMARIZEMIN = 195;
  public int JJTSUMMARIZEAND = 196;
  public int JJTSUMMARIZEOR = 197;
  public int JJTSUMMARIZEXOR = 198;
  public int JJTSUMMARIZEEXACTLY = 199;
  public int JJTSUMMARIZEEXACTLYDISTINCT = 200;
  public int JJTSUMMARIZEUNION = 201;
  public int JJTSUMMARIZEXUNION = 202;
  public int JJTSUMMARIZEDUNION = 203;
  public int JJTSUMMARIZEINTERSECT = 204;
  public int JJTFNINVOKE = 205;
  public int JJTARGLIST = 206;
  public int JJTAGGCOUNT = 207;
  public int JJTAGGSUM = 208;
  public int JJTAGGAVG = 209;
  public int JJTAGGMAX = 210;
  public int JJTAGGMIN = 211;
  public int JJTAGGAND = 212;
  public int JJTAGGOR = 213;
  public int JJTAGGXOR = 214;
  public int JJTAGGUNION = 215;
  public int JJTAGGXUNION = 216;
  public int JJTAGGDUNION = 217;
  public int JJTAGGINTERSECT = 218;
  public int JJTTUPLE = 219;
  public int JJTTUPLECOMPONENT = 220;
  public int JJTRELATION = 221;
  public int JJTRELATIONDUM = 222;
  public int JJTRELATIONDEE = 223;
  public int JJTRELATIONHEADING = 224;
  public int JJTHEADING = 225;
  public int JJTTUPLEEXPRESSIONCOMMALIST = 226;
  public int JJTATTRIBUTESPEC = 227;
  public int JJTIDENTIFIER = 228;
  public int JJTDEREFERENCE = 229;
  public int JJTCHARACTER = 230;
  public int JJTSTRINGLITERAL = 231;
  public int JJTINTEGER = 232;
  public int JJTRATIONAL = 233;
  public int JJTTRUE = 234;
  public int JJTFALSE = 235;


  public String[] jjtNodeName = {
    "Evaluate",
    "Code",
    "Statement",
    "void",
    "GetOperatorReturnType",
    "GetHeading",
    "GetSignature",
    "Write",
    "Writeln",
    "Output",
    "Announce",
    "Execute",
    "Set",
    "Lambda",
    "ExternalOpDef",
    "UserOpDef",
    "UserOpReturns",
    "UserOpUpdates",
    "UserOpSynonym",
    "UserOpVersion",
    "UserOpBody",
    "ReturnExpression",
    "UserOpParameters",
    "ParmDef",
    "DropOperator",
    "DropRelvar",
    "DropConstraint",
    "DropType",
    "OpSignature",
    "OpType",
    "TypeRefCommalist",
    "TypeDef",
    "TypeDefExternal",
    "TypeDefInternal",
    "TypeDefInternalOptOrdinal",
    "TypeDefInternalOptOrdered",
    "TypeDefInternalOptUnion",
    "SingleInheritanceIsDef",
    "MultipleInheritanceIsDef",
    "ScalarTypeName",
    "PossrepInitialiser",
    "PossrepInitialiserAssignments",
    "PossrepDef",
    "PossrepDefIdentifier",
    "PossrepDefConstraintDef",
    "PossrepDefComponentCommalist",
    "PossrepDefComponent",
    "PossrepConstraintDef",
    "SpecialisationConstraintDef",
    "DerivedPossrepDef",
    "DerivedPossrepDefOptIdentifier",
    "DerivedPossrepComponentDef",
    "VarDef",
    "VarRelvarReal",
    "VarRelvarPrivate",
    "VarRelvarPublic",
    "VarRelvarVirtual",
    "VarRelvarExternal",
    "KeyDefList",
    "KeyDef",
    "VarScalarOrTuple",
    "VarTypeAndOptionalInit",
    "VarInit",
    "VarArray",
    "DatabaseConstraint",
    "Type",
    "TypeSameTypeAs",
    "TypeTuple",
    "TypeRelation",
    "SameHeadingAs",
    "RelationArrayLoad",
    "TransactionBegin",
    "TransactionCommit",
    "TransactionRollback",
    "CaseStatement",
    "CaseWhenList",
    "CaseWhen",
    "CaseElse",
    "IfStatement",
    "ElseStatement",
    "DoLoop",
    "WhileLoop",
    "ForLoop",
    "Call",
    "Assignment",
    "Assign",
    "Insert",
    "DInsert",
    "Delete",
    "IDelete",
    "UpdateStatement",
    "DeleteParameter",
    "DeleteWhere",
    "UpdateWhere",
    "UpdateAssignment",
    "Expression",
    "AttributeFrom",
    "TupleFrom",
    "With",
    "WithNameIntroCommalist",
    "WithNameIntro",
    "TClose",
    "ArrayDereference",
    "FnInvokeAnonymous",
    "AlgOrder",
    "AlgWhere",
    "Or",
    "Xor",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "TupleIn",
    "AlgUnion",
    "AlgXunion",
    "AlgDUnion",
    "AlgIntersect",
    "AlgMinus",
    "AlgIMinus",
    "AlgJoin",
    "AlgTimes",
    "AlgCompose",
    "AlgSemijoin",
    "AlgSemiminus",
    "AlgRename",
    "AlgWrap",
    "AlgUnwrap",
    "AlgUngroup",
    "AlgDivide",
    "OrderItemCommalist",
    "OrderItemAsc",
    "OrderItemDesc",
    "AlgDividePerOptional",
    "AlgProject",
    "Group",
    "WrappingItem",
    "RenamingList",
    "RenamingSimple",
    "RenamingPrefix",
    "RenamingSuffix",
    "AttributeNameList",
    "AllBut",
    "AttributeNameCommalist",
    "Add",
    "Subtract",
    "Concatenate",
    "Times",
    "Divide",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "CaseExpression",
    "CaseWhenListExpression",
    "CaseWhenExpression",
    "IfExpression",
    "Substitute",
    "NadicHeading",
    "NadicUnion",
    "NadicXunion",
    "NadicDUnion",
    "NadicIntersect",
    "NadicJoin",
    "NadicTimes",
    "NadicCompose",
    "NadicOr",
    "NadicXor",
    "NadicAnd",
    "NadicCount",
    "NadicSum",
    "NadicAvg",
    "NadicMax",
    "NadicMin",
    "Exactly",
    "ExpressionCommalist",
    "BooleanExpressionCommalist",
    "HeadingExpCommalist",
    "Extend",
    "ExtendList",
    "ExtendItem",
    "Summarize",
    "SummarizePerOrBy",
    "SummarizePer",
    "SummarizeBy",
    "SummarizeItems",
    "SummarizeItem",
    "SummarizeCount",
    "SummarizeCountDistinct",
    "SummarizeSum",
    "SummarizeSumDistinct",
    "SummarizeAvg",
    "SummarizeAvgDistinct",
    "SummarizeMax",
    "SummarizeMin",
    "SummarizeAnd",
    "SummarizeOr",
    "SummarizeXor",
    "SummarizeExactly",
    "SummarizeExactlyDistinct",
    "SummarizeUnion",
    "SummarizeXunion",
    "SummarizeDUnion",
    "SummarizeIntersect",
    "FnInvoke",
    "ArgList",
    "AggCount",
    "AggSum",
    "AggAvg",
    "AggMax",
    "AggMin",
    "AggAnd",
    "AggOr",
    "AggXor",
    "AggUnion",
    "AggXunion",
    "AggDUnion",
    "AggIntersect",
    "Tuple",
    "TupleComponent",
    "Relation",
    "RelationDum",
    "RelationDee",
    "RelationHeading",
    "Heading",
    "TupleExpressionCommalist",
    "AttributeSpec",
    "Identifier",
    "Dereference",
    "Character",
    "StringLiteral",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=91a4b683a9249e1203b31dbdf829f58e (do not edit this line) */
