ln -s ~/git/Rel/_Deployment/RelDBMS.jar .
ln -s ~/git/Rel/_Deployment/commons-codec-1.4.jar .
ln -s ~/git/Rel/_Deployment/commons-logging-1.1.1.jar .
ln -s ~/git/Rel/_Deployment/ecj-4.4.2.jar .
ln -s ~/git/Rel/_Deployment/httpclient-4.1.3.jar .
ln -s ~/git/Rel/_Deployment/httpclient-cache-4.1.3.jar .
ln -s ~/git/Rel/_Deployment/httpcore-4.1.4.jar .
ln -s ~/git/Rel/_Deployment/httpmime-4.1.3.jar .
ln -s ~/git/Rel/_Deployment/je-6.2.31.jar .
ln -s ~/git/Rel/_Deployment/rel0000.jar .
ln -s ~/git/Rel/_Deployment/relclient.jar .
ln -s ~/git/Rel/_Deployment/relshared.jar .
