ln -s ~/git/Rel/_Deployment/RelDBMS.jar .
ln -s ~/git/Rel/_Deployment/commons-codec-1.4.jar .
ln -s ~/git/Rel/_Deployment/commons-logging-1.1.1.jar .
ln -s ~/git/Rel/_Deployment/ecj-4.4.2.jar .
ln -s ~/git/Rel/_Deployment/httpclient-4.1.3.jar .
ln -s ~/git/Rel/_Deployment/httpclient-cache-4.1.3.jar .
ln -s ~/git/Rel/_Deployment/httpcore-4.1.4.jar .
ln -s ~/git/Rel/_Deployment/httpmime-4.1.3.jar .
ln -s ~/git/Rel/_Deployment/je-7.0.6.jar .
ln -s ~/git/Rel/_Deployment/rel0000.jar .
ln -s ~/git/Rel/_Deployment/relclient.jar .
ln -s ~/git/Rel/_Deployment/relshared.jar .
ln -s ~/git/Rel/_Deployment/commons-configuration-1.6.jar .
ln -s ~/git/Rel/_Deployment/commons-lang-2.4.jar .
ln -s ~/git/Rel/_Deployment/dom4j-1.6.1.jar .
ln -s ~/git/Rel/_Deployment/hadoop-core-1.1.2.jar .
ln -s ~/git/Rel/_Deployment/hbase-0.94.9.jar .
ln -s ~/git/Rel/_Deployment/log4j-1.2.15.jar .
ln -s ~/git/Rel/_Deployment/mysql-connector-java-5.1.25-bin.jar .
ln -s ~/git/Rel/_Deployment/poi-3.9-20121203.jar .
ln -s ~/git/Rel/_Deployment/poi-ooxml-3.9-20121203.jar .
ln -s ~/git/Rel/_Deployment/poi-ooxml-schemas-3.9-20121203.jar .
ln -s ~/git/Rel/_Deployment/protobuf-java-2.2.0.jar .
ln -s ~/git/Rel/_Deployment/slf4j-api-1.4.3.jar .
ln -s ~/git/Rel/_Deployment/slf4j-log4j12-1.4.3.jar .
ln -s ~/git/Rel/_Deployment/stax-api-1.0.1.jar .
ln -s ~/git/Rel/_Deployment/xmlbeans-2.3.0.jar .
ln -s ~/git/Rel/_Deployment/zookeeper-3.4.5.jar .
